
services:
  db:
    image: postgres:16
    container_name: db_infinity
    volumes:
      - ../data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - .env


  pgadmin:
    image: elestio/pgadmin
    container_name: pgadmin_infinity
#    ports:
#      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    env_file:
      - .env


  bot:
    build:
      context: ..
      dockerfile: docker/dockerfiles/DockerfileBot
      args:
        - --no-cache
    container_name: bot_infinity
    volumes:
      - ../bot:/app
      - ../photo:/app/photo
      - ../switch:/app/switch
      - ../logs/exchange_bot:/app/logs
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env


#  bot_antispam:
#    build:
#      context: ..
#      dockerfile: docker/dockerfiles/DockerfileAntispam
#      args:
#        - --no-cache
#    container_name: bot_antispam
#    volumes:
#      - ../bot_antispam:/app
#      - ../bot/db:/app/db
#      - ../bot/enums:/app/enums
#      - ../photo:/app/photo
#      - ../logs/bot_antispam:/app/logs
#    restart: unless-stopped
#    depends_on:
#      - db
#    env_file:
#      - .env

  web:
    build:
      context: ..
      dockerfile: docker/dockerfiles/DockerfileAdmin
      args:
        - --no-cache
    container_name: web_infinity
    volumes:
      - ../admin_infinity:/app
      - ../photo:/app/media/photo
      - ../switch:/app/switch
      - ../logs/django:/app/logs

    restart: unless-stopped
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env


  nginx:
    image: nginx:latest
    container_name: nginx_infinity
    ports:
      - "81:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d/base.conf:/etc/nginx/conf.d/base.conf
      - ../admin_infinity/staticfiles:/var/html/static/
      - ../admin_infinity/staticfiles:/var/html/staticfiles/
      - ../admin_infinity/media:/var/html/media/
      - ../photo:/var/html/media/photo/
      - ../logs/nginx:/var/log/nginx
    restart: unless-stopped
    depends_on:
      - web


  redis:
    image: redis:latest
    container_name: redis_infinity


volumes:
  pgadmin_data:
  static_value:
  media_value:

